# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160513_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('title', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='grop_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='grop_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='grop_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='grop_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='grop_0',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blog.Post'),
        ),
    ]
