# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_document_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
